package com.excel.service.impl;

import com.excel.mapper.CampsUserDetailMapper;
import com.excel.model.CampsUserDetail;
import com.excel.model.CampsUserDetailExample;
import com.excel.service.CampsUserDetailService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class CampsUserDetailServiceImpl extends ServiceSupport<String, CampsUserDetail, CampsUserDetailExample, CampsUserDetailMapper> implements CampsUserDetailService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camps_user_detail
     *
     * @mbg.generated Wed Apr 28 10:54:23 CST 2021
     */
    @Resource
    private CampsUserDetailMapper campsUserDetailMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camps_user_detail
     *
     * @mbg.generated Wed Apr 28 10:54:23 CST 2021
     */
    @PostConstruct
    private void initService() {
        super.mapper = campsUserDetailMapper;
    }
}