package com.excel.service.impl;

import com.excel.mapper.DataMapper;
import com.excel.model.Data;
import com.excel.model.DataExample;
import com.excel.service.DataService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class DataServiceImpl extends ServiceSupport<Integer, Data, DataExample, DataMapper> implements DataService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    @Resource
    private DataMapper dataMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    @PostConstruct
    private void initService() {
        super.mapper = dataMapper;
    }
}