package com.excel.model;

import com.excel.model.CampsUserDetailExample.C;
import com.excel.model.CampsUserDetailExample.Criteria;
import java.io.Serializable;
import java.sql.Types;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import mboog.support.example.AbstractExample;
import mboog.support.example.AbstractGeneratedCriteria;
import mboog.support.example.CInterface;
import mboog.support.example.CItem;
import mboog.support.example.ColumnListAble;
import mboog.support.example.PaginationAble;

@SuppressWarnings("unused")
public class CampsUserDetailExample extends AbstractExample<CampsUserDetailExample, Criteria, C> implements Serializable, ColumnListAble<CampsUserDetailExample, C, C>, PaginationAble<CampsUserDetailExample> {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camps_user_detail
     *
     * @mbg.generated Wed Apr 28 10:54:23 CST 2021
     */
    public CampsUserDetailExample() {
        supplier = Criteria::new;
        initColumnList(C.class);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camps_user_detail
     *
     * @mbg.generated Wed Apr 28 10:54:23 CST 2021
     */
    protected abstract static class GeneratedCriteria extends AbstractGeneratedCriteria<Criteria> {

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String pattern, String value) {
            addCriterionPattern("id like", pattern, value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String pattern, String value) {
            addCriterionPattern("id not like", pattern, value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDetailIdIsNull() {
            addCriterion("detail_id is null");
            return (Criteria) this;
        }

        public Criteria andDetailIdIsNotNull() {
            addCriterion("detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andDetailIdEqualTo(String value) {
            addCriterion("detail_id =", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdNotEqualTo(String value) {
            addCriterion("detail_id <>", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdGreaterThan(String value) {
            addCriterion("detail_id >", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdGreaterThanOrEqualTo(String value) {
            addCriterion("detail_id >=", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdLessThan(String value) {
            addCriterion("detail_id <", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdLessThanOrEqualTo(String value) {
            addCriterion("detail_id <=", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdLike(String pattern, String value) {
            addCriterionPattern("detail_id like", pattern, value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdNotLike(String pattern, String value) {
            addCriterionPattern("detail_id not like", pattern, value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdIn(List<String> values) {
            addCriterion("detail_id in", values, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdNotIn(List<String> values) {
            addCriterion("detail_id not in", values, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdBetween(String value1, String value2) {
            addCriterion("detail_id between", value1, value2, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdNotBetween(String value1, String value2) {
            addCriterion("detail_id not between", value1, value2, "detailId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("session_id is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("session_id is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("session_id =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("session_id <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("session_id >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("session_id >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("session_id <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("session_id <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLike(String pattern, String value) {
            addCriterionPattern("session_id like", pattern, value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotLike(String pattern, String value) {
            addCriterionPattern("session_id not like", pattern, value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<String> values) {
            addCriterion("session_id in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<String> values) {
            addCriterion("session_id not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("session_id between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("session_id not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String pattern, String value) {
            addCriterionPattern("username like", pattern, value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String pattern, String value) {
            addCriterionPattern("username not like", pattern, value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUserIpIsNull() {
            addCriterion("user_ip is null");
            return (Criteria) this;
        }

        public Criteria andUserIpIsNotNull() {
            addCriterion("user_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUserIpEqualTo(String value) {
            addCriterion("user_ip =", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotEqualTo(String value) {
            addCriterion("user_ip <>", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpGreaterThan(String value) {
            addCriterion("user_ip >", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpGreaterThanOrEqualTo(String value) {
            addCriterion("user_ip >=", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpLessThan(String value) {
            addCriterion("user_ip <", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpLessThanOrEqualTo(String value) {
            addCriterion("user_ip <=", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpLike(String pattern, String value) {
            addCriterionPattern("user_ip like", pattern, value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotLike(String pattern, String value) {
            addCriterionPattern("user_ip not like", pattern, value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpIn(List<String> values) {
            addCriterion("user_ip in", values, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotIn(List<String> values) {
            addCriterion("user_ip not in", values, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpBetween(String value1, String value2) {
            addCriterion("user_ip between", value1, value2, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotBetween(String value1, String value2) {
            addCriterion("user_ip not between", value1, value2, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserMacIsNull() {
            addCriterion("user_mac is null");
            return (Criteria) this;
        }

        public Criteria andUserMacIsNotNull() {
            addCriterion("user_mac is not null");
            return (Criteria) this;
        }

        public Criteria andUserMacEqualTo(String value) {
            addCriterion("user_mac =", value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacNotEqualTo(String value) {
            addCriterion("user_mac <>", value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacGreaterThan(String value) {
            addCriterion("user_mac >", value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacGreaterThanOrEqualTo(String value) {
            addCriterion("user_mac >=", value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacLessThan(String value) {
            addCriterion("user_mac <", value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacLessThanOrEqualTo(String value) {
            addCriterion("user_mac <=", value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacLike(String pattern, String value) {
            addCriterionPattern("user_mac like", pattern, value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacNotLike(String pattern, String value) {
            addCriterionPattern("user_mac not like", pattern, value, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacIn(List<String> values) {
            addCriterion("user_mac in", values, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacNotIn(List<String> values) {
            addCriterion("user_mac not in", values, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacBetween(String value1, String value2) {
            addCriterion("user_mac between", value1, value2, "userMac");
            return (Criteria) this;
        }

        public Criteria andUserMacNotBetween(String value1, String value2) {
            addCriterion("user_mac not between", value1, value2, "userMac");
            return (Criteria) this;
        }

        public Criteria andVlanIdIsNull() {
            addCriterion("vlan_id is null");
            return (Criteria) this;
        }

        public Criteria andVlanIdIsNotNull() {
            addCriterion("vlan_id is not null");
            return (Criteria) this;
        }

        public Criteria andVlanIdEqualTo(String value) {
            addCriterion("vlan_id =", value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdNotEqualTo(String value) {
            addCriterion("vlan_id <>", value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdGreaterThan(String value) {
            addCriterion("vlan_id >", value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdGreaterThanOrEqualTo(String value) {
            addCriterion("vlan_id >=", value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdLessThan(String value) {
            addCriterion("vlan_id <", value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdLessThanOrEqualTo(String value) {
            addCriterion("vlan_id <=", value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdLike(String pattern, String value) {
            addCriterionPattern("vlan_id like", pattern, value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdNotLike(String pattern, String value) {
            addCriterionPattern("vlan_id not like", pattern, value, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdIn(List<String> values) {
            addCriterion("vlan_id in", values, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdNotIn(List<String> values) {
            addCriterion("vlan_id not in", values, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdBetween(String value1, String value2) {
            addCriterion("vlan_id between", value1, value2, "vlanId");
            return (Criteria) this;
        }

        public Criteria andVlanIdNotBetween(String value1, String value2) {
            addCriterion("vlan_id not between", value1, value2, "vlanId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String pattern, String value) {
            addCriterionPattern("user_id like", pattern, value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String pattern, String value) {
            addCriterionPattern("user_id not like", pattern, value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(LocalDateTime value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(LocalDateTime value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(LocalDateTime value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<LocalDateTime> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camps_user_detail
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 28 10:54:23 CST 2021
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table camps_user_detail
     *
     * @mbg.generated Wed Apr 28 10:54:23 CST 2021
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]
		//--------------------------------------------------					
						ID(1, Types.VARCHAR, false, "id"),					
						DETAIL_ID(2, Types.VARCHAR, false, "detail_id"),					
						SESSION_ID(2, Types.VARCHAR, false, "session_id"),					
						USERNAME(2, Types.VARCHAR, false, "username"),					
						USER_IP(2, Types.VARCHAR, false, "user_ip"),					
						USER_MAC(2, Types.VARCHAR, false, "user_mac"),					
						VLAN_ID(2, Types.VARCHAR, false, "vlan_id"),					
						USER_ID(2, Types.VARCHAR, false, "user_id"),					
						CREATETIME(2, Types.TIMESTAMP, false, "createTime");

        C(int types, int jdbcType, boolean delimited, String columnName) {
            init(new CItem(types, jdbcType, delimited, columnName, null , "`", "`"));
        }
    }
}