package com.excel.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class CampsUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camps_user.userId
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camps_user.username
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camps_user.desc
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camps_user.createTime
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    private LocalDateTime createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camps_user
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camps_user.userId
     *
     * @return the value of camps_user.userId
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camps_user.userId
     *
     * @param userid the value for camps_user.userId
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camps_user.username
     *
     * @return the value of camps_user.username
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camps_user.username
     *
     * @param username the value for camps_user.username
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camps_user.desc
     *
     * @return the value of camps_user.desc
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camps_user.desc
     *
     * @param desc the value for camps_user.desc
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camps_user.createTime
     *
     * @return the value of camps_user.createTime
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public LocalDateTime getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camps_user.createTime
     *
     * @param createtime the value for camps_user.createTime
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camps_user
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", desc=").append(desc);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}