package com.excel.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Data implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.id
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.name
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.nationality
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.mobile
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.email
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.createTime
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private LocalDateTime createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.dataSource
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private String datasource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.otherInfo
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private String otherinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.address
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.id
     *
     * @return the value of data.id
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.id
     *
     * @param id the value for data.id
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.name
     *
     * @return the value of data.name
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.name
     *
     * @param name the value for data.name
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.nationality
     *
     * @return the value of data.nationality
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.nationality
     *
     * @param nationality the value for data.nationality
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.mobile
     *
     * @return the value of data.mobile
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.mobile
     *
     * @param mobile the value for data.mobile
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.email
     *
     * @return the value of data.email
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.email
     *
     * @param email the value for data.email
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.createTime
     *
     * @return the value of data.createTime
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public LocalDateTime getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.createTime
     *
     * @param createtime the value for data.createTime
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.dataSource
     *
     * @return the value of data.dataSource
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.dataSource
     *
     * @param datasource the value for data.dataSource
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.otherInfo
     *
     * @return the value of data.otherInfo
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public String getOtherinfo() {
        return otherinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.otherInfo
     *
     * @param otherinfo the value for data.otherInfo
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setOtherinfo(String otherinfo) {
        this.otherinfo = otherinfo == null ? null : otherinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.address
     *
     * @return the value of data.address
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.address
     *
     * @param address the value for data.address
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", nationality=").append(nationality);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", createtime=").append(createtime);
        sb.append(", datasource=").append(datasource);
        sb.append(", otherinfo=").append(otherinfo);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}