package com.excel.mapper;

import com.excel.model.CampsUser;
import com.excel.model.CampsUserExample;
import mboog.support.mapper.ReadMapper;
import mboog.support.mapper.UpsertMapper;
import mboog.support.mapper.WriteMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CampsUserMapper extends UpsertMapper<String, CampsUser, CampsUserExample>, ReadMapper<String, CampsUser, CampsUserExample>, WriteMapper<String, CampsUser, CampsUserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camps_user
     *
     * @mbg.generated Wed Apr 28 09:49:25 CST 2021
     */
    default CampsUser selectByPrimaryKeyWithColumns(String primaryKey, boolean include, CampsUserExample.C... cs) {
        CampsUserExample example = new CampsUserExample();
        if (include) {
                example.includeColumns(cs);
        } else {
                example.excludeColumns(cs);
        }
        example.or(cri -> cri
               .andUseridEqualTo(primaryKey)
        );
        return selectByExampleSingleResult(example);
    }
}