package com.excel.mapper;

import com.excel.model.CampsUserDetail;
import com.excel.model.CampsUserDetailExample;
import mboog.support.mapper.ReadMapper;
import mboog.support.mapper.UpsertMapper;
import mboog.support.mapper.WriteMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CampsUserDetailMapper extends UpsertMapper<String, CampsUserDetail, CampsUserDetailExample>, ReadMapper<String, CampsUserDetail, CampsUserDetailExample>, WriteMapper<String, CampsUserDetail, CampsUserDetailExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camps_user_detail
     *
     * @mbg.generated Wed Apr 28 10:54:23 CST 2021
     */
    default CampsUserDetail selectByPrimaryKeyWithColumns(String primaryKey, boolean include, CampsUserDetailExample.C... cs) {
        CampsUserDetailExample example = new CampsUserDetailExample();
        if (include) {
                example.includeColumns(cs);
        } else {
                example.excludeColumns(cs);
        }
        example.or(cri -> cri
               .andIdEqualTo(primaryKey)
        );
        return selectByExampleSingleResult(example);
    }
}