package com.excel.mapper;

import com.excel.model.Data;
import com.excel.model.DataExample;
import mboog.support.mapper.ReadMapper;
import mboog.support.mapper.UpsertMapper;
import mboog.support.mapper.WriteMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DataMapper extends UpsertMapper<Integer, Data, DataExample>, ReadMapper<Integer, Data, DataExample>, WriteMapper<Integer, Data, DataExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated Tue Jan 19 15:43:08 CST 2021
     */
    default Data selectByPrimaryKeyWithColumns(Integer primaryKey, boolean include, DataExample.C... cs) {
        DataExample example = new DataExample();
        if (include) {
                example.includeColumns(cs);
        } else {
                example.excludeColumns(cs);
        }
        example.or(cri -> cri
               .andIdEqualTo(primaryKey)
        );
        return selectByExampleSingleResult(example);
    }
}